Add back <cwchar> for wcwidth in src/unicode.hh
On a musl system with clang 18.1.8 linking against libc++, 64ed046e breaks
the build with

  src/unicode.hh:105:24: error: use of undeclared identifier 'wcwidth'
    105 |     const auto width = wcwidth((wchar_t)c);

though this doesn't happen on the same system with gcc 14.2.0 linking
against libstdc++.

Include <cwchar> again so wcwidth() is properly defined.