Fail rename-session instead of creating overlong socket paths
Commit 9cf8a3ccd (Check for buffer overflow when constructing the socket path., 2022-04-07)
made

	$ kak -s $(printf %0100d)

fail but forgot to do the same for

	$ kak -e "rename-session $(printf %0100d)"

which silently succeeds, only to fail at the next

	$ echo nop | kak -p $(printf %0100d)
	Fatal error: socket path too long: '/run/user/1000/kakoune/0000...'

Let's fail earlier.

While at it, don't validate "m_session" redundantly.

I'm not sure if we should validate the socket names in "kak -clear";
I guess it doesn't matter.