rc windowing kitty: proper error if remote control is disabled
Commit 15bf1c7614 (updated kitty integration to use the no-response
switch, 2018-09-01) added the "--no-response" switch.  Presumably to
suppress stdout on successful "kitty @".  But that didn't seem necessary
because for "kitty @ new-window" we already ignored the output, and
"kitty @ focus-window" doesn't seem to produce output on success.

When ~/.config/kitty/kitty.conf does not include "allow_remote_control yes",
then "kitty @" commands will fail and print an error to stderr

	$ kitty @ launch
	Error: Remote control is disabled

and, if "--no-response" was given, kitty writes the error to the PTY(!)
instead of to stderr.  This makes such user errors easily discoverable
inside interactive shells:

	$ kitty @ launch --no-response
	$ kitty-cmd{"ok": false, "error": "Remote control is disabled"}

But it can cause confusion in a modal editor; if in normal mode,
we'll execute "k", "i" and insert the rest into the calling buffer.
This can be reproduced with

	$ HOME=$(mktemp -d) kitty -e kak -e new

As reported in https://github.com/kakoune-lsp/kakoune-lsp/issues/889,
this is especially surprising with support scripts like "jump.kak"
whose ":jump" command runs "try %{ focus %opt{jumpclient} }", inserting
garbage into the buffer.
When kitty's remote control is disabled this command should fail,
and the "try" should silence that failure (except for *debug* logs).

Replace the --no-response switch with a redirect of stdout to /dev/null.
Also add a proper error (using "fail") to point the user towards the
root cause.

Reported-by: v@anomalous.eu